parameters:
#    odiseo_lan.example.class: Odiseo\LanBundle\Example

services:
#    odiseo_lan.example:
#        class: %odiseo_lan.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
