parameters:
    my_user_provider.class: Odiseo\LanBundle\Security\User\TwitterUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager, {twitter: twitter_id}]
        
    odiseo_lan.backend.menu_builder:
        class: Odiseo\LanBundle\Menu\BackendMenuBuilder
        arguments: ["@knp_menu.factory", "@security.context"]
        
    odiseo_lan.backend.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: odiseo_lan.backend.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: backend_main_menu } # The alias is what is used to retrieve the menu
            
    lan.form.type.user:
        class: Odiseo\LanBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: lan_user }
            
    lan.form.type.twitteruser:
        class: Odiseo\LanBundle\Form\Type\TwitterUserType
        tags:
            - { name: form.type, alias: lan_twitteruser }
            
    lan.form.type.configuration:
        class: Odiseo\LanBundle\Form\Type\ConfigurationType
        tags:
            - { name: form.type, alias: lan_configuration }
