gecko_backend:
    resource: "@GeckoBackendBundle/Resources/config/routing/main.yml"
    prefix:   /admin

odiseo_lan:
    resource: "@OdiseoLanBundle/Resources/config/routing/main.yml"
    prefix:   /
