security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false
                    
        admin:
            pattern: /admin.*
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/dashboard
                use_referer: true
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous: true
            context:   lan_admin
            
        main:
            pattern: ^/.*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    twitter:           "/login/check-twitter"
                login_path:        /login
                failure_path:      /login
 
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:       true
            anonymous:    true
            context:   lan
            
        login:
            pattern:  ^/login$
            security: false
 
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/css.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin.*, role: ROLE_ADMIN }
        
        - { path: ^/media.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
