security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false
                    
        admin:
            pattern: /admin.*
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/dashboard
                use_referer: true
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous: true
            context:   lan_admin
            
        main:
            pattern: /.*
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                default_target_path: /
                use_referer: true
            logout:
                path: /logout
                target: /
            anonymous: true
            context:   lan
            
    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/css.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin.*, role: ROLE_ADMIN }
        
        - { path: ^/media.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
