Odiseo\LanBundle\Entity\Configuration:
    type: entity
    table: configuration
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateBegin:
            column: date_begin
            type: date
        dateEnd:
            column: date_end
            type: date
        beginMailSended:
            column: beginMailSended
            type: boolean
            default: false
        endMailSended:
            column: endMailSended
            type: boolean
            default: false 
    lifecycleCallbacks: {  }
