Odiseo\LanBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        twitter_id:
            column: twitter_id
            type: string
            length: 255
            nullable: true
        twitter_access_token:
            column: twitter_access_token
            type: string
            length: 255
            nullable: true
        twitter_profile_image_url:
            column: twitter_profile_image_url
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update  
        fullName:
            column: full_name
            type: string
            length: 255
            nullable: true  
        dni:
            column: dni
            type: string
            length: 255
            nullable: true
        edad:
            column: edad
            type: string
            length: 255
            nullable: true 
        telefono:
            column: telefono
            type: string
            length: 255
            nullable: true
        provincia:
            column: provincia
            type: string
            length: 255
            nullable: true
        mail:
            column: mail
            type: string
            length: 255
            nullable: true     
        acceptNewsletter:
            column: acceptNewsletter
            type: boolean
            nullable: true 
         
    oneToMany:
        twitters:
            targetEntity: TwitterUser
            mappedBy: user
    lifecycleCallbacks: {  }
