Odiseo\LanBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        twitter_id:
            column: twitter_id
            type: string
            length: 255
            nullable: true
        twitter_access_token:
            column: twitter_access_token
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update  
    oneToMany:
        twitters:
            targetEntity: TwitterUser
            mappedBy: user
    lifecycleCallbacks: {  }
