gecko_backend_index:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: odiseo_lan_backend_dashboard
        permanent: true

#sylius_backend_settings:
#    resource: @SyliusWebBundle/Resources/config/routing/backend/settings.yml
#    prefix: /settings

#gecko_backend_security:
#    resource: @GeckoBackendBundle/Resources/config/routing/security.yml
