odiseo_lan_twitteruser_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: lan.controller.twitteruser:indexAction
        _sylius:
            template: OdiseoLanBundle:Backend/TwitterUser:index.html.twig
            paginate: 100
            
odiseo_lan_twitteruser_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: lan.controller.twitteruser:createAction
        _sylius:
            template: OdiseoLanBundle:Backend/TwitterUser:create.html.twig
            redirect: odiseo_lan_twitteruser_update

odiseo_lan_twitteruser_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: lan.controller.twitteruser:updateAction
        _sylius:
            template: OdiseoLanBundle:Backend/TwitterUser:update.html.twig
            redirect: odiseo_lan_twitteruser_update

odiseo_lan_twitteruser_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: lan.controller.twitteruser:deleteAction
        _sylius:
            redirect: odiseo_lan_twitteruser_index