odiseo_lan_frontend_homepage:
    pattern: /
    defaults: { _controller: OdiseoLanBundle:Frontend/Main:index }
        
lan_register:
    pattern: /register
    defaults: { _controller: OdiseoLanBundle:Frontend/Main:register }
    
lan_send_tweet:
    pattern: /send-tweet
    defaults: { _controller: OdiseoLanBundle:Frontend/Main:sendTweet }